title:            LeeKonyu
description:      "这里是学习博客。"

github: LeeKonyu
weibo: Leekiwi
zhihu: leekiwi
zhuanlan: leekiwi
disqus_shortname: leekiwi

url: //blog.leeky.top
menu:
  - title: 'Categories'
    url: '/categories'
  - title: 'About'
    url: '/about'
  - title: 'Github'
    url: 'https://github.com/LeeKonyu'

timezone:    Africa/El_Aaiun
locale:      zh_CN
lang:      zh-cmn-Hans
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:year-:month-:day/:title.html
assetUrl: //blog.leeky.top/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==



google_analytics: UA-57207999-1
baidu_verify: kxGpkpWG7G
google_verify: DbapjTyfmMvvmkuA1GiGcXMqgPQrtgxeUTGY-MrEOYw

paginate: 7
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true

showBuyCoffee: true
payImage: //github-blog-1302744225.cos.ap-chongqing.myqcloud.com/io.blog/wx_paymecoffee.png?q-sign-algorithm=sha1&q-ak=AKIDJ3dKQ2xnde6cLrIzQh7LZhxX8bz5A2egYBIsGNFjc_iTFtLR74mC8fm0y_xoWuNV&q-sign-time=1597742784;1597746384&q-key-time=1597742784;1597746384&q-header-list=&q-url-param-list=&q-signature=dc5fbabb1f184da8f2854460479f4918ec462048&x-cos-security-token=dfeRQcI9H4trPmTjM9Uxsqy9z91KAg8Oe356f6723e6f6d1c2716f77d1231b136u4xgvCzNvq3NBrI1T8CiHZ7s1nljLzMmFc7fRNHM931hEr4ZP6_M96ot-oEDF9-V1wq0c92zLRjV-W0q-wWjfnREICHAIQDiwDgccnTmrtaMqc9w2oGYk2vhW9ogAnA7zU0-osFQWbOLlLVHxwMXECeSYAOGfDn0dXYm5GTu414

include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE", "package.json","node_modules"]
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
plugins: [jekyll-paginate,jekyll-sitemap,jekyll-feed]

port: 6688